### ISSUE TITLE
Default shown in usage is incorrect when the option is supplied

### ISSUE THREAD

**Issue by ericmillin** [urfave/cli#1181] opened 2020-08-27 12:36 UTC
## my urfave/cli version is

2.1.1

## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

If a command fails due to invalid usage, values assigned to valid options are used to populate the defaults.

## To reproduce

1. Create the command `foo`
2. Add the flag `fizz` and mark it as required.
3. Add the IntFlag `bang` with the default value of `1`.
4. Run the command `foo --bang 2`

## Observed behavior

The `default` in the usage text will show `(default: 2)`

## Expected behavior

The `default` in the usage text will show `(default: 1)`

**Comment by asahasrabuddhe** [comment] 2020-10-30 18:34
![1181](https://user-images.githubusercontent.com/25657923/97744084-a2cf8a80-1b0c-11eb-849d-e9b97deea2e4.PNG)

Unable to reproduce issue. This was the example I tried.

**Comment by lynncyrin** [comment] 2021-02-10 07:01
This looks like a duplicate of https://github.com/urfave/cli/issues/1206, but I would have to dive into the code to say that with confidence.

**Comment by dearchap** [comment] 2022-10-10 01:27
Unable to reproduce.

**Closed by dearchap** 2022-10-10 01:27 UTC
Labels: kind/bug, area/v2, status/triage
