### ISSUE TITLE
Allow custom text for printed strings

### ISSUE THREAD

**Issue by m-horky** [urfave/cli#1724] opened 2023-04-20 15:52 UTC
## Checklist

* [x] Are you running the latest v3 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v3 manual is [here](https://github.com/urfave/cli/blob/main/docs/v3/manual.md).
* [x] Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

I'd like to be able to change any (English) string that is printed to the console. It would be useful for translating applications (is this issue a duplicate of #980?) -- not being able to alter texts during runtime prevents that.

## Solution description

Similarly to how it is possible to change texts of `VersionFlag` or `HelpFlag`, I'd like to be able to access:
- `command.go`: `Incorrect Usage:` in `Run()`
- `context.go`: `no such flag -%s` in `Set()`
- `errors.go`: most of the error messages
- `flag.go`: `default` in `formatDefault()`
- `parse.go`: const `lag provided but not defined: -`
- and possibly more

## Describe alternatives you've considered

An alternative could be to add full i18n support as per #980. But that also comes with its set of challenges -- mainly how to allow external applications to extend or include the translations of this project in theirs (languages not supported by this package, or to change the provided translation for whatever reasons).

**Comment by dearchap** [comment] 2023-05-16 14:23
@m-horky Thanks for this. yes i18n support is planned. If you have any ideas on how to do this it would be greatly appreciated

**Comment by dearchap** [comment] 2023-05-21 22:43
@m-horky yes it looks like a duplicate of #980 . I will get working on this. Thanks for raising the issue

**Closed** 2023-06-10 00:07 UTC
Labels: status/triage, area/v3
