### ISSUE TITLE
BUG: cli.v1/altsrc

### ISSUE THREAD

**Issue by dixonwille** [urfave/cli#518] opened 2016-09-02 18:32 UTC
The import statement in `altsrc` on the latest `v1` tag is pointing to the master branch `github.com/urfave/cli` not `gopkg.in/urfave/cli.v1`

**Comment by jszwedko** [comment] 2016-09-03 20:13
This is a duplicate of #505 (and fixed by #512) and will be included in the next release. Please let me know if this doesn't address your concerns.

Thanks!

**Closed by jszwedko** 2016-09-03 20:13 UTC

**Comment by dixonwille** [comment] 2016-09-03 20:17
Thanks didn't realize they had the same issue on V2?
