### ISSUE TITLE
Dependency package download failed

### ISSUE THREAD

**Issue by lvbin2012** [urfave/cli#901] opened 2019-09-24 05:05 UTC
The package "https://github.com/cpuguy83/go-md2man/v2/md2man" used in docs.go could not been download any more. It needs to be fixed please.

**Comment by zzell** [comment] 2019-09-25 13:05
Downgrading to v1.21.0 worked for me.

**Comment by lynncyrin** [comment] 2019-10-02 02:50
@lvbin2012 @zzell @vulcan-lin @lbarman can any of you show me a CI build that reproduces this?

**Comment by saschagrunert** [comment] 2019-10-02 07:35
@lvbin2012 did you run this with enabled go modules? How does the output of `go env` look like?

**Comment by johnnylei** [comment] 2019-10-06 15:43
i met this problem also; "urfave/cli/docs.go:11:2: cannot find package "github.com/cpuguy83/go-md2man/v2/md2man"";
$ go env
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build572817432=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

```

**Comment by lynncyrin** [comment] 2019-10-06 19:53
Still waiting for someone to give me a full reproduction in CI 🙂

**Comment by lynncyrin** [comment] 2019-10-08 02:03
Hey FYI for everyone following this, I still don't have enough information to debug this! Please help me out with a CI build I can look at, so I can have the full context of the failure

**Comment by johnnylei** [comment] 2019-10-08 02:39
> Still waiting for someone to give me a full reproduction in CI 🙂

Excuse me, What's "CI" means?

**Comment by saschagrunert** [comment] 2019-10-08 06:27
> > Still waiting for someone to give me a full reproduction in CI slightly_smiling_face
> 
> Excuse me, What's "CI" means?

Can you provide us a reproducible environment, like a container and some commands? :)

**Comment by johnnylei** [comment] 2019-10-08 07:15
go version:go version go1.7.1 linux/amd64
os: ubuntu 14.04
kernel:3.13.0-83-generic
command: $ go build main.go
```
package main

import (
	"fmt"
	"github.com/urfave/cli"
	"log"
	"os"
	"os/exec"
	"syscall"
)

func main() {
	app := cli.NewApp()
	app.Commands = []cli.Command{
		{
			Name: "run",
			Usage: `create a container with namespace and cgroups limit mydocker run -ti [command]`,
			Flags: []cli.Flag{
				cli.BoolFlag{
					Name: "ti",
				},
			},
			Action: func(c *cli.Context) error {
				if len(c.Args()) < 1 {
					return fmt.Errorf("missing container command")
				}

				cmd := exec.Command("/proc/self/exe", "init", c.Args().Get(0))
				cmd.SysProcAttr = &syscall.SysProcAttr{
					Cloneflags:syscall.CLONE_NEWIPC | syscall.CLONE_NEWUTS | syscall.CLONE_NEWPID | syscall.CLONE_NEWNS | syscall.CLONE_NEWNET,
				}

				if tty := c.Bool("ti"); tty {
					cmd.Stdin = os.Stdin
					cmd.Stdout = os.Stdout
					cmd.Stderr = os.Stderr
				}

				if err := cmd.Start(); err != nil {
					log.Fatal(err)
				}

				if err := cmd.Wait(); err != nil {
					log.Fatal(err)
				}

				return nil
			},
		},
		{
			Name: "init",
			Usage: "init for container",
			Action: func(c *cli.Context) error {
				command := c.Args().Get(0)
				if err := syscall.Mount("proc", "/proc", "proc", uintptr(syscall.MS_NOEXEC | syscall.MS_NOSUID | syscall.MS_NOSUID), ""); err != nil {
					log.Fatal(err)
				}

				argv := []string{command}
				if err:= syscall.Exec(command, argv, os.Environ()); err !=nil {
					log.Fatal(err)
				}
				return nil
			},
		},
	}

	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}
```
message
```
../../urfave/cli/docs.go:11:2: cannot find package "github.com/cpuguy83/go-md2man/v2/md2man" in any of:
	/usr/local/go/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOROOT)
	/root/go/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOPATH)
```

**Comment by lynncyrin** [comment] 2019-10-08 07:22
@johnnylei that's better, but I need a bit more 🔍 if it's in a public repo, can you link me to the repo? Otherwise can you give me:

- your go.mod / go.sum file
- the command you are running when you get the error above

**Comment by johnnylei** [comment] 2019-10-08 07:29
> @johnnylei that's better, but I need a bit more 🔍 if it's in a public repo, can you link me to the repo? Otherwise can you give me:
> 
> * your go.mod / go.sum file
> * the command you are running when you get the error above

https://github.com/johnnylei/my_docker

**Comment by AudriusButkevicius** [comment] 2019-10-08 07:33
We use go modules, this requires go 1.12 or even 1.13. your go binary does not support go modules and fetches random versions of our dependencies.

**Comment by johnnylei** [comment] 2019-10-08 08:00
> We use go modules, this requires go 1.12 or even 1.13. your go binary does not support go modules and fetches random versions of our dependencies.

thanks, i fixed this problem using `git checkout v1.17.0`;

**Comment by lynncyrin** [comment] 2019-10-08 08:27
Pre-emptively: please keep this issue open, I'm not confident that johnnylei's issue is the same as everyone else's.

**Comment by lbarman** [comment] 2019-10-08 10:12
Hi @lynncyrin , sorry for being unresponsive. The problem does *not* happen when I download everything on a fresh computer; I must have some package stuck somewhere, however `go get -u ./...` is currently not solving the issue. But I can confirm that if you start from 0 (no Go packages on a VM), I don't get the issue.

**Comment by lynncyrin** [comment] 2019-10-09 03:56
@lbarman does that mean this issue https://github.com/dedis/prifi/issues/213 is resolved also?

**Comment by lynncyrin** [comment] 2019-10-09 03:57
👋 @lvbin2012 one last ping on this 🙏 can you go through some of the same debugging instructions that are described above? If not, I can close this ♻️

**Comment by tharvik** [comment] 2019-10-09 07:50
@lynncyrin [dedis/prifi#213](https://github.com/dedis/prifi/issues/213) is resolved (or rather, not reproducable), looks like a transient issue.

**Comment by lynncyrin** [comment] 2019-10-12 07:17
As far as I can tell, nobody is still experiencing an issue here that we can solve on our end - so I'm closing this.

Please feel free to comment again if you have a similar issue, ideally with debugging information included. Thanks everyone! ✨

**Closed by lynncyrin** 2019-10-12 07:17 UTC
Labels: status: triage, type: bug
