### ISSUE TITLE
strange comportement with quotes

### ISSUE THREAD

**Issue by blackrez** [urfave/cli#714] opened 2018-02-20 15:39 UTC
Hello,

I don't know if it is the right comportement

```
./greet --lang spanish 
Hola Nefertiti

./greet '--lang spanish' 
Incorrect Usage. flag provided but not defined: -lang spanish

./greet ' --lang spanish'
Hello  --lang spanish

```

This is annoying when used with openshift.

**Comment by lynncyrin** [comment] 2019-08-09 01:40
That's definitely weird behavior! We should definitely make sure all 3 of those cases behave in the same way 👍

**Comment by AudriusButkevicius** [comment] 2019-08-11 23:29
I think the only badness here is case 2 should behave like case 3.

**Comment by saschagrunert** [comment] 2019-09-14 09:47
Does this issue still exist? I cannot reproduce it any more with the latest version... 👀

**Comment by dearchap** [comment] 2022-12-08 00:04
This is the behaviour of the ```ls``` command

```
$ ls "-al"
total 20
drwxr-xr-x  2 dearchap dearchap 4096 Dec  7 18:54 .
drwxrwxrwx 43 dearchap dearchap 4096 Dec  7 18:52 ..
-rw-r--r--  1 dearchap dearchap  283 Dec  7 18:54 go.mod
-rw-r--r--  1 dearchap dearchap  764 Dec  7 18:54 go.sum
-rw-r--r--  1 dearchap dearchap  227 Dec  7 18:56 main.go
dearchap@LP-W10:~/go/src/github.com/dearchap/issue_534$ ls " -al"
ls: cannot access ' -al': No such file or directory
```

I think its upto the user to ensure that there are no spaces before the "-". 

Closing this.

**Closed by dearchap** 2022-12-08 00:04 UTC
Labels: kind/bug, help wanted, area/v2, status/confirmed
