### ISSUE TITLE
Possbile StringFlag Validation Bug 

### ISSUE THREAD

**Issue by IcE4k777** [urfave/cli#600] opened 2017-02-23 01:54 UTC
**Works as expected:**
`myApp subCommand --StringFlag myArgument`

**Works as expected, cli handles printing usage as no argument is given to --StringFlag:** 
`myApp subCommand --StringFlag`

**Not working as expected:**
`myApp subCommand --StringFlag --myBoolFlag`

It appears cli is just reading the next string after --StringFlag and considering that as the argument to --StringFlag, however, cli should print usage as no argument is really provided to --StringFlag. What do you guys think? Is this to much input validation for cli to deal with?

**Comment by jszwedko** [comment] 2017-04-24 22:36
:+1: I could see this as a possible enhancement, but would require some preprocessing as the current behavior is due to how the `flag` standard library opts to handle it.

**Comment by lynncyrin** [comment] 2020-02-26 05:09
ok stale bot 😆 

I marked this as `help wanted` 🙏

**Comment by xordspar0** [comment] 2020-06-22 22:43
I'm not sure if my opinion counts for anything, but I prefer the current behavior. I wouldn't want cli to be too smart and try to figure out my intention. Maybe I really did want to pass `--myBoolFlag` as a string argument.

**Comment by meatballhat** [comment] 2022-04-22 23:24
I'm adding this to the 3.x milestone as something of a punt since I suspect the answer is going to be using a different argument parser than stdlib `flag`

**Comment by dearchap** [comment] 2022-11-06 19:44
Duplicate of #424

**Closed by dearchap** 2022-11-06 19:44 UTC
Labels: kind/feature, help wanted, area/v3
