### ISSUE TITLE
some commands decide not to respect `--help`

### ISSUE THREAD

**Issue by whyrusleeping** [urfave/cli#478] opened 2016-07-09 20:21 UTC
I'm not sure what causes it, but some of the commands i write execute their action when run with `--help`.

Repro:
```
go get github.com/whyrusleeping/gx
gx deps --help
```

**Comment by meatballhat** [comment] 2016-07-10 21:54
@whyrusleeping Hey!  Is this on `master`, `v2`, or something else?

**Comment by meatballhat** [comment] 2016-07-10 21:56
Also, dupe of #477 looks like, so closing in favor

**Closed by meatballhat** 2016-07-10 21:56 UTC
Labels: bug
