### ISSUE TITLE
StringSliceFlag will show it's value as default if failed in Before:

### ISSUE THREAD

**Issue by arykalin** [urfave/cli#1076] opened 2020-02-25 17:18 UTC
## my urfave/cli version is

_**( Put the version of urfave/cli that you are using here )**_

## Checklist

* [v] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [v] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [v] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [v] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

StringSliceFlag will show it's actual value as default if failed in Before.

## To reproduce

```
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/urfave/cli/v2"
)

func main() {
	app := &cli.App{
		EnableBashCompletion: true,
		Commands: []*cli.Command{
			{
				Name: "wat",
				Flags: []cli.Flag{
					&cli.StringSliceFlag{Name: "dance-move"},
				},
				Before: func(context *cli.Context) error {
					return fmt.Errorf("I fail")
				},
			},
		},
	}
	err := app.Run(os.Args)
	if err != nil {
		log.Fatal(err)
	}
}
```

## Observed behavior
./main wat --dance-move 1111
```
2020/02/25 20:11:17 I fail
NAME:
   urfave_cli wat - 

USAGE:
   urfave_cli wat [command options] [arguments...]

OPTIONS:
   --dance-move value  (default: "1111")
   --help, -h          show help (default: false)
   

Process finished with exit code 1
```

## Expected behavior

./main wat --dance-move 1111
```
2020/02/25 20:11:17 I fail
NAME:
   urfave_cli wat - 

USAGE:
   urfave_cli wat [command options] [arguments...]

OPTIONS:
   --dance-move value
   --help, -h          show help (default: false)
   

Process finished with exit code 1
```

## Additional context

If the issue relates to a specific open source Github repo, please link that repo here.

If you can reproduce this issue with a public CI system, please link a failing build here.

## Want to fix this yourself?

We'd love to have more contributors on this project! If the fix for this bug is easily explained and very small, free free to create a pull request for it.
## Run `go version` and paste its output here

```
go version go1.13.4 linux/amd64
```

## Run `go env` and paste its output here

```
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build885487390=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by lynncyrin** [comment] 2020-02-26 07:33
@arykalin can you remove the sections of the issue template that you didn't fill out? thanks ✨ 

This feels like the same issue as https://github.com/urfave/cli/pull/981, or possibly it's just conceptually similar.

At any rate, I'm fairly certain that I understand the bug here 👍 marking this as `help wanted`

**Comment by dearchap** [comment] 2022-09-12 09:46
Problem is in a release that is very very old. Cant reproduce on latest release. Closing.

**Closed by dearchap** 2022-09-12 09:46 UTC
Labels: kind/bug, help wanted, area/v2, status/confirmed
