### ISSUE TITLE
IntSliceFlag failes at parsing -flag=1,2,3

### ISSUE THREAD

**Issue by cvik** [urfave/cli#1097] opened 2020-03-26 14:00 UTC
## my urfave/cli version is

_**2.2.0**_

## Checklist

* [X] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [X] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [X] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.
- My project is automatically downloading the latest version.

## Describe the bug
When using `IntSliceFlag` it complain with:
`Incorrect Usage: invalid value "1,2,3" for flag -zones: strconv.ParseInt: parsing "1,2,3": invalid syntax`
This works for `StringSliceFlag`.

## To reproduce
Add a `IntFlagSlice{Name="flag"}` and call it with `-flag=1,2,3`.

## Observed behavior
It gives the error described above.

## Expected behavior

I expect it to parse this correctly and then be able to get it with `cli.Context.IntSlice("flag")`.

## Run `go version` and paste its output here

```
go version go1.14 linux/amd64
```

**Comment by lynncyrin** [comment] 2020-03-30 23:40
Seems like a pretty straightforward bug! Marking this as `help wanted` 👍

**Comment by dearchap** [comment] 2022-08-19 01:29
@cvik This is not a bug. For non string slice flags you need to give --flag=1 --flag=2 --flag=3 to get the slice contents. The reason it works for string slice is that the string "1,2,3" is a valid string. However if you look at the string slice it would be of length 1 with string "1,2,3" instead of "1", "2", "3"

**Closed** 2022-08-28 13:21 UTC
Labels: kind/question, area/v2, status/confirmed
