### ISSUE TITLE
Ordering of arguments and flags impact one another

### ISSUE THREAD

**Issue by mntlty** [urfave/cli#1733] opened 2023-05-18 23:34 UTC
## My urfave/cli version is

_** v2.25.3**_

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management
- My project is using go modules.

## Describe the bug

Ordering of arguments and flags impact one another, causing a flag value to be set or unset depending on whether it comes before or after an argument. This can result in a silent error where the flag name is recognized but the value isn't set.

## To reproduce

Using the flag example from https://cli.urfave.org/v2/examples/flags/ (copying below for ease of reference)

```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/urfave/cli/v2"
)

func main() {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "lang",
				Value: "english",
				Usage: "language for the greeting",
			},
		},
		Action: func(cCtx *cli.Context) error {
			name := "Nefertiti"
			if cCtx.NArg() > 0 {
				name = cCtx.Args().Get(0)
			}
			if cCtx.String("lang") == "spanish" {
				fmt.Println("Hola", name)
			} else {
				fmt.Println("Hello", name)
			}
			return nil
		},
	}

	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}
```

## Observed behavior

```bash
# argument
$ ./example my-name
Hello my-name
# flag
$ ./example --lang spanish        
Hola Nefertiti
# flag before argument
$ ./example --lang spanish my-name 
Hola my-name
# argument before flag
$ ./example my-name --lang spanish
Hello my-name
```

## Expected behavior

`$ ./example my-name --lang spanish` and `./example --lang spanish my-name ` should both set the `--lang` flag to the value `spanish`

## Additional context

N/A

## Want to fix this yourself?

We'd love to have more contributors on this project! If the fix for
this bug is easily explained and very small, feel free to create a
pull request for it.

## Run `go version` and paste its output here

```
go version go1.20.4 darwin/arm64
```

## Run `go env` and paste its output here

```
# paste `go env` output in here
```

**Comment by dearchap** [comment] 2023-05-20 21:05
@mntlty This is by design. This issue has been fixed in v3 wherein a flag can be marked as persistent allowing it to flow through to subcommands. This will not be backported to v2 as v2 is on a feature freeze and maintenance only

**Closed** 2023-05-21 14:38 UTC
Labels: kind/bug, area/v2, status/triage

**Comment by mntlty** [comment] 2023-05-21 18:02
@dearchap in that case, looking forward to V3!

I was confused by the part in your response about subcommands - in the example there are no subcommands, only flags and arguments to defined commands.

**Comment by fiatjaf** [comment] 2024-07-09 10:12
@mntlty please upvote this official feature request here: https://github.com/urfave/cli/issues/1950
