### ISSUE TITLE
StringSliceFlag doesn't support Destination

### ISSUE THREAD

**Issue by tboerger** [urfave/cli#603] opened 2017-03-04 17:26 UTC
Multiple flag types support a `Destination` attribute to directly bind the value to a variable, except `StringSliceFlag`. Can we add this flag there as well?

**Comment by jszwedko** [comment] 2017-03-04 21:28
@tboerger it isn't readily apparent from the documentation, but it actually augments the `Value` field since, in this case, it is a pointer. I agree that `Destination` would be better for consistency though.

**Comment by tboerger** [comment] 2017-03-05 09:30
Value is something different than Destination :)

**Comment by tboerger** [comment] 2017-03-05 09:31
But let's see what happens if I assign the default value to the destination variable.

**Comment by asahasrabuddhe** [comment] 2019-08-07 15:25
@urfave/cli what is your opinion on this? We can accomodate this change but this would most likely break the public API. Should we defer this to v2 instead?

**Comment by tboerger** [comment] 2019-08-07 17:42
I am already using gopkg.in/urfave/cli.v2 for ages, but still missing this feature :(

**Comment by lynncyrin** [comment] 2019-08-08 06:00
I'm not totally sure I understand the ask here! Perhaps an example would help?

**Comment by tboerger** [comment] 2019-08-08 13:57
## Works

```
type Config struct {
	Foo string
}

cfg := Config{}

flags := []cli.Flag{
	&cli.StringFlag{
		Name:        "foo",
		Value:       "bar",
		Usage:       "usage",
		Destination: &cfg.Foo,
	},
}
```

## Fails

```
type Config struct {
	Foo []string
}

cfg := Config{}

flags := []cli.Flag{
	&cli.StringSliceFlag{
		Name:        "foo",
		Value:       "bar",
		Usage:       "usage",
		Destination: &cfg.Foo,
	},
}
```

I would expect to be able to use `Destination` also for `StringSliceFlag`, which currently doesn't work, so currently I got to bind it to my config struct like this, which is not that nice as `Destination` would be much cleaner:

```
Before: func(c *cli.Context) error {
	if len(c.StringSlice("foo")) > 0 {
		// StringSliceFlag doesn't support Destination
		cfg.Foo = c.StringSlice("foo")
	}
}
```

I hope these examples are detailed enough :)

**Comment by lynncyrin** [comment] 2019-08-08 15:22
Gotcha! We should definitely support this 👍👍👍

**Comment by tboerger** [comment] 2019-12-20 14:35
Is it more complicated to get this integrated? Can I help somehow? Getting `Destination` for the slices would reduce the whole boilerplate code within https://github.com/drone-plugins which are all based on urfave/cli.

**Comment by lynncyrin** [comment] 2020-02-26 05:12
👋 this is still a valid issue! I'm just gonna close it as a duplicate of https://github.com/urfave/cli/issues/1075

**Closed by lynncyrin** 2020-02-26 05:12 UTC
Labels: area/v2, help wanted, kind/feature, status/confirmed

**Comment by tboerger** [comment] 2020-02-26 08:34
Uhm... You mean #1075 is a duplicate of this, but whatever. I have not received any further information anyway.

**Comment by lynncyrin** [comment] 2020-02-27 01:05
Did I mean that? I haven't seen any formal rules anywhere about precedents and duplicates. Apologies if I was rude 🙏
