### ISSUE TITLE
How to implement something like an OptionFlag?

### ISSUE THREAD

**Issue by marcofranssen** [urfave/cli#1154] opened 2020-06-19 09:38 UTC
## How to implement something like an OptionFlag

I'm looking to implement a Flag which can have a few predefined values.

E.g.

```
mycli --output json
mycli --output xml
```

Is there a way to implement this using the existing flags while also informing the user of the cli what are the available options?

If not would it make sense to add this OptionFlag? I would be happy to make a PR for that with some guidance.

**Comment by lynncyrin** [comment] 2020-07-02 03:56
To rephrase the question - are if asking if there's a builtin way to implement a flag that gives users a set of choices from a predefined list? Something like `Choices: []string{'json', 'xml'}`?

**Comment by marcofranssen** [comment] 2020-07-02 11:47
@lynncyrin yes that is exactly what I meant.

**Comment by lynncyrin** [comment] 2020-07-02 17:13
Makes sense! There's no obvious builtin way to implement this, but I've implemented a few "manual" versions of it. I don't happen to have that code on-hand, though.

**Comment by marcofranssen** [comment] 2020-07-03 11:56
@lynncyrin would be great if you could dig it up and share a snippet here with the community. I'm happy to take that snippet of your further to integrate it here.

**Comment by MarvinJWendt** [comment] 2020-08-24 03:47
Ping @lynncyrin

**Comment by nielsvaneck** [comment] 2020-09-17 02:34
This was previously requested in #620

**Comment by MarvinJWendt** [comment] 2020-12-16 12:39
Not stale

**Comment by dearchap** [comment] 2021-02-06 02:43
Here is how I implemented it using GenericFlag and a custom value

`type choiceValue struct {
	choices []string // the choices that this value can take
	value   *string  // the actual value
}

func (v *choiceValue) Set(value string) error {
	for _, choice := range v.choices {
		if strings.Compare(choice, value) == 0 {
			*v.value = value
			return nil
		}
	}
	return fmt.Errorf("%s is not a valid option. need %+v", value, v.choices)
}

func (v *choiceValue) String() string {
	if v.value == nil {
		return ""
	}
	return *v.value
}`

Then 

`
v c string
&cli.GenericFlag{
			Name: "foo",
			Usage: "the foo option",
			Value: &choiceValue{
				choices: []string{"bar", "zzzz", "some", "thing"},
				value:   &c,
			},`

**Comment by dearchap** [comment] 2021-02-08 01:18
There is a PR for this feature. https://github.com/urfave/cli/pull/1234

**Comment by abdennour** [comment] 2021-07-23 23:22
Wy Wy Wy! should we open it again?

**Comment by dearchap** [comment] 2021-07-25 00:10
There are 2 ways to approach this. One is with PR #1234 . The other is using validations as in PR #1261 . Its upto the maintainers to choose the way forward.

**Comment by dearchap** [comment] 2022-10-21 21:55
This is a duplicate of #786 .

**Closed by dearchap** 2022-10-21 21:55 UTC
Labels: kind/question, area/v2, status/triage, pinned
