### ISSUE TITLE
GlobalStringSlice flags cause a kernel panic

### ISSUE THREAD

**Issue by ellisju** [urfave/cli#383] opened 2016-05-02 22:18 UTC
I assume this is an issue for both the GlobalStringSlice and the StringSlice structs.  In my code I am simply trying to do something like:

`config.DB.Servers = ctx.GlobalStringSlice("dbServers")`

Where both config.DB.Servers and the output of ctx.GlobalStringSlice are of type []string.  This causes the following runtime error on that line:

```
panic: interface conversion: flag.Value is *flag.stringValue, not *cli.StringSlice [recovered]
	panic: interface conversion: flag.Value is *flag.stringValue, not *cli.StringSlice

goroutine 1 [running]:
...
github.com/codegangsta/cli.(*Context).GlobalStringSlice(0xc8200a17c0, 0x475a470, 0xa, 0x0, 0x0, 0x0)
	/Users/jellis225/gocode/src/github.com/codegangsta/cli/context.go:109 +0x14d
```

That particular line in the cli package is calling "lookupStringSlice" where it is attempting to return:

`return (f.Value.(*StringSlice)).Value()`

It looks like the cast to *StringSlice is what is causing issues.

**Comment by meatballhat** [comment] 2016-05-03 01:54
@ellisju Thanks for the report!  I suspect what's happening here is that the lookup funcs simply aren't being defensive enough.  I could not reproduce your error in a minimal case where there was only one matching global flag:

``` go
package main

import (
        "fmt"
        "os"

        "github.com/codegangsta/cli"
)

func main() {
        app := cli.NewApp()

        app.Flags = []cli.Flag{
                cli.StringSliceFlag{
                        Name:  "hats",
                        Value: &cli.StringSlice{"top", "fruit"},
                },
        }

        app.Action = func(ctx *cli.Context) error {
                fmt.Printf("%#v\n", ctx.GlobalStringSlice("hats"))
                return nil
        }

        app.Run(os.Args)
}
```

I *do* get the error when attempting to look up a flag of another type:

``` go
package main

import (
        "fmt"
        "os"

        "github.com/codegangsta/cli"
)

func main() {
        app := cli.NewApp()

        app.Flags = []cli.Flag{
                cli.StringFlag{
                        Name:  "hats",
                        Value: "top",
                },
        }

        app.Commands = []cli.Command{
                cli.Command{
                        Name: "do",
                        Flags: []cli.Flag{
                                cli.StringSliceFlag{
                                        Name:  "hats",
                                        Value: &cli.StringSlice{"top", "fruit"},
                                },
                        },
                        Action: func(ctx *cli.Context) error {
                                defer func() {
                                        if r := recover(); r != nil {
                                                fmt.Printf("%s\n    -> %#v\n", r, r)
                                        }
                                }()
                                fmt.Printf("%#v\n", ctx.GlobalStringSlice("hats"))
                                return nil
                        },
                },
        }

        app.Run(os.Args)
}
```

### so:

I think this is still a bug, *but* I strongly suspect your code in question defines a `"dbServers"` flag at multiple levels, and the one being looked up is not a string slice.

**Comment by jszwedko** [comment] 2016-05-03 03:47
That is possible. Could you paste a snippet of code that reproduces your issue @ellisju ?

**Comment by ellisju** [comment] 2016-05-03 15:04
I double-checked and I am not defining the flag at multiple levels.  I will try to get a snippet for reproduction up today.

**Comment by meatballhat** [comment] 2016-06-22 13:05
@ellisju *bump* 😸 Any update?

**Comment by jszwedko** [comment] 2016-07-13 21:52
Closing this out, but please reopen if you see this again @ellisju

**Closed by jszwedko** 2016-07-13 21:52 UTC
Labels: bug
