### ISSUE TITLE
Run flag actions when Value is set

### ISSUE THREAD

**Issue by samlaf** [urfave/cli#1973] opened 2024-09-29 03:39 UTC
Believe that Actions are only run when a flag is set. This means that when I have an Action which I want to run even on the default Value, I have to set HasBeenSet to true, like below
```
var MaxBlobLengthBytes = 0
[...] // pseudo code for flag definition below
		cli.StringFlag{
			Name:    "foo",
			Value:   "16MiB",
			HasBeenSet: true, // set this to true to force action to run
			Action: func(_ *cli.Context, maxBlobLengthStr string) error {
				// parse the string to a uint64 and set the maxBlobLengthBytes var to be used by ReadConfig()
				numBytes, err := utils.ParseBytesAmount(maxBlobLengthStr)
				if err != nil {
					return fmt.Errorf("failed to parse max blob length flag: %w", err)
				}
				if numBytes == 0 {
					return fmt.Errorf("max blob length is 0")
				}
				if numBytes > MaxAllowedBlobSize {
					return fmt.Errorf("excluding disperser constraints on max blob size, SRS points constrain the maxBlobLength configuration parameter to be less than than %d bytes", MaxAllowedBlobSize)
				}
				MaxBlobLengthBytes = numBytes
				return nil
			},
		},
```

Is this intended behavior? Should we not also run an action when a Value is set?

**Comment by dearchap** [comment] 2024-09-29 21:28
@samlaf That is the intended behaviour. You cannot trigger a flag action on default. Also the ```hasBeenSet``` is a private field in StringFlag so you cannot really set it.

**Comment by samlaf** [comment] 2024-09-29 21:34
@dearchap hmm that's weird, because it's public on my import and I've been using it with this behavior (tested that it's working):
<img width="953" alt="image" src="https://github.com/user-attachments/assets/0783d27a-6c95-4b33-a551-45338eb6479a">

Could you explain or link me to a place where the intended behaviour is explained? My use case seems like a valid behaviour to me.

**Comment by dearchap** [comment] 2024-09-30 00:49
@samlaf you are actually using v2. The v3 tag on this issue confused me. Here is the code which decides whether to call a flag action or not. https://github.com/urfave/cli/blob/v2-maint/app.go#L473 . Also note that v2 is in maint mode so any changes in this behavior need to be done on v3.

**Comment by samlaf** [comment] 2024-09-30 01:31
@dearchap oh yes my bad… opened it initially woth the v3 template but then realized I was using v2 so erased the template msg but left the tag.

Is v3 production ready right now? And if I switch to it how would I reproduce the current behavior I’m using of running the action on the default value (nice to have default be something human readable as it’s shown as an example to users in the —help output)

**Comment by dearchap** [comment] 2024-09-30 14:19
v3 is in beta state and is mostly usable.

**Comment by dearchap** [comment] 2024-10-26 10:32
@samlaf Would you like to make a PR for this ?

**Comment by samlaf** [comment] 2024-10-26 10:37
Don’t have time these days so can’t promise anything. Unless you point me to the exact/approximate where the change would be. Not familiar with Urfave internal codebase, let alone v3.

**Comment by dearchap** [comment] 2024-10-26 17:18
You can look at command.Run which calls runFlagActions

**Comment by dearchap** [comment] 2024-10-31 12:31
@samlaf It doesnt really make sense to run a Flag Action all the time. It defeats the purpose. It would just be a block of code that you could put in the Command.Action . I'm going to close this issue .

**Closed by dearchap** 2024-10-31 12:31 UTC
Labels: status/triage, status/waiting-for-response, area/v3

**Comment by dearchap** [comment] 2024-10-31 19:07
I agree but this is a very atypical use case.
