### ISSUE TITLE
Why design global options need to be before subcommands?

### ISSUE THREAD

**Issue by lizhifengones** [urfave/cli#1391] opened 2022-05-08 06:31 UTC
Global options need to appear before subcommands, not anywhere, why are they designed this way?

This is not the same as spf13/cobra. `In urfave/cli, global options are not visible in subcommands`.

I like cobra's global options, but urfave/cli is simpler, that's why I use urfave/cli. Hope someone can explain my doubts...
```sh
# ./bin/test-cmd --debug aaa  (work)
# ./bin/test-cmd aaa --debug
2022/05/08 14:23:57 flag provided but not defined: -debug
```

**Comment by fjl** [comment] 2022-05-11 20:15
I have to say, I find this extremely annoying as well. We use urfave/cli in go-ethereum, and are kind of stuck with it because we have so much code relying on it.

It would be nice to be able to tweak this behavior using e.g.

```
var app = cli.App{
    ...
    AllowAllFlagsInSubcommands: true
}
```

and the implementation of it would be straightforward, just construct the flag set a bit differently.

**Comment by tonglil** [comment] 2022-05-13 23:02
Funny, just stumbled upon this UX issue today as well.

**Comment by Icarus9913** [comment] 2022-05-26 15:57
Yeah, as @tonglil said. It would be nice to show `Global options` through the whole cmd cli phase from top to bottom.
For users to get understand the global options better.

**Comment by yxxhero** [comment] 2022-06-30 00:54
any update?

**Comment by dearchap** [comment] 2022-10-21 19:07
Duplicate of #1113

**Closed by dearchap** 2022-10-21 19:07 UTC
Labels: kind/question, area/v2, status/triage
