### ISSUE TITLE
Enum Support

### ISSUE THREAD

**Issue by coen-hyde** [urfave/cli#602] opened 2017-02-26 22:23 UTC
Option values often only support a limited set of valid values. It would be helpful to have CLI enforce valid options and auto generate help docs listing valid options.

**Comment by jszwedko** [comment] 2017-02-27 02:37
:+1: this is possible via the `GenericFlag`, but I'll mark this as a possible enhancement.

Thanks!

**Comment by BlueBeN82** [comment] 2017-08-19 14:16
+1

**Comment by maheshvra** [comment] 2018-01-19 05:47
+1

**Comment by doronbehar** [comment] 2020-05-26 08:24
I'd still like to see this dear bot.

**Comment by dearchap** [comment] 2022-10-21 19:13
Duplicate of #786 . Enum is a special case of flag validation in that the input is restricted to a certain set of strings.

**Closed by dearchap** 2022-10-21 19:13 UTC
Labels: kind/feature, status/claimed, area/v2
