### ISSUE TITLE
Help text should automatically wrap based on term width

### ISSUE THREAD

**Issue by nikkolasg** [urfave/cli#287] opened 2015-10-20 09:26 UTC
When we got a long text description in Usage, it should automatically wrap and make a nice display.
A bit like what "man" does, it automatically rewraps the text so it fits nicely in the current terminal session.

**Comment by wikiwi** [comment] 2015-11-13 17:36
+1

**Comment by syossan27** [comment] 2016-01-06 12:37
+1

**Comment by immesys** [comment] 2016-09-05 21:21
+1

**Comment by hickeng** [comment] 2016-10-10 15:51
and should be able to handle `\n` in the various command and flag descriptions, indenting appropriately.

**Comment by JensRantil** [comment] 2017-08-07 06:42
...or simply wrap at 80 characters, which is considered a common default and also adheres to [general readability best-practises](https://baymard.com/blog/line-length-readability).

**Comment by lynncyrin** [comment] 2019-09-10 06:37
This feature is now `in review` - @urfave/cli please add a 👍 or 👎 to the top post if you're in favor or against this feature being added!

**Comment by saschagrunert** [comment] 2020-01-16 14:53
@lynncyrin we should move forward with this one. Wrapping based on the term width seems a sane default. :)

**Comment by lynncyrin** [comment] 2020-01-16 21:07
👀 this is now ready for anyone to work on!

**Comment by xordspar0** [comment] 2020-03-08 23:14
> ...or simply wrap at 80 characters, which is considered a common default and also adheres to [general readability best-practises](https://baymard.com/blog/line-length-readability).

I agree that an 80 character limit would be easier to read. It would also be easier to implement. That said, I don't want to bikeshed this issue. Whoever actually does the work to implement this will have my vote.

**Comment by mostynb** [comment] 2020-05-06 06:42
I will try to make #1119 implement a basic version of this feature.

**Comment by mostynb** [comment] 2020-08-04 08:07
Bump.

**Comment by mostynb** [comment] 2020-11-03 06:19
Bump.

**Comment by mostynb** [comment] 2021-02-02 08:01
Bump.

**Comment by dearchap** [comment] 2022-10-21 18:47
@mostynb Are you up to making a PR for this ?

**Comment by dearchap** [comment] 2022-10-21 18:57
Duplicate of #674

**Closed by dearchap** 2022-10-21 18:57 UTC
Labels: kind/feature, help wanted, area/v2, status/confirmed

**Comment by mostynb** [comment] 2022-10-21 18:59
I added line-wrapping support in #287, but the terminal's width detection is not automatic (to avoid adding new dependencies/adding binary size). Here's an example of how client code can specify the line-wrap length: https://github.com/urfave/cli/pull/1119/files#diff-4d3f36d62cad94424544bb84fc93b33b73ffe3491a4ddca81a7f825539afc19cR1161-R1169
