### ISSUE TITLE
StringSliceFlag context.IsSet Panic Go 1.7

### ISSUE THREAD

**Issue by arteev** [urfave/cli#516] opened 2016-08-31 10:47 UTC
Go 1.7 
For: StringSliceFlag
....
ctx   *cli.Context
...
if ctx.IsSet("names") ... 

we have panic:

usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/urfave/cli.HandleAction.func1(0xc4200ceaf8)
	/home/user/go/src/github.com/urfave/cli/app.go:478 +0x247
panic(0x7c1120, 0xc420013d20)
	/usr/local/go/src/runtime/panic.go:458 +0x243
reflect.flag.mustBe(0x16, 0x19)
	/usr/local/go/src/reflect/value.go:201 +0xae
reflect.Value.FieldByName(0x7ce5a0, 0xc4200145c0, 0x16, 0x813898, 0x6, 0x815701, 0x9, 0xc4200ce120)
	/usr/local/go/src/reflect/value.go:794 +0x49
github.com/urfave/cli.(*Context).IsSet.func3(0x81572b, 0x9)
	/home/user/go/src/github.com/urfave/cli/context.go:82 +0xf1
github.com/urfave/cli.eachName(0x81572b, 0xb, 0xc4200ce200)
	/home/user/go/src/github.com/urfave/cli/flag.go:63 +0xb5
github.com/urfave/cli.(*Context).IsSet(0xc42009c640, 0x81412e, 0x7, 0x5)
	/home/user/go/src/github.com/urfave/cli/context.go:94 +0x1b8
github.com/arteev/dsql/commands.(*cliFlags).getvalue(0xc42000ce10, 0x7f7b02, 0x81412e, 0x7, 0x81233e, 0x1, 0x7f7b00, 0xc4200943f0, 0xc4200943f0)

**Comment by jszwedko** [comment] 2016-09-03 21:29
Hi @arteev,

Could you provide a code snippet that reproduces this issue? It is unclear what how it is getting in that state just from the stack trace.

Thank you!

**Comment by arteev** [comment] 2016-09-07 10:18
Hi @jszwedko! Of course!

It's worked!

```func main() {
	app := cli.NewApp()
	app.Flags = []cli.Flag{
		cli.StringSliceFlag{
			Name:  "a",
			Usage: "use it",
		},
	}
	app.Action = func(c *cli.Context) error {
		if c.IsSet("a") {
			fmt.Println("String:", c.String("a"))
		}
		return nil
	}
	app.Run(os.Args)
}```



It did not work!

```func main() {
	app := cli.NewApp()
	app.Flags = []cli.Flag{
		&cli.StringSliceFlag{
			Name:  "a",
			Usage: "use it",
		},
	}
	app.Action = func(c *cli.Context) error {
		if c.IsSet("a") {
			fmt.Println("String:", c.String("a"))
		}
		return nil
	}
	app.Run(os.Args)
}```

go run main.go -> panic!
go run main.go -a=123 -> OK!

**Comment by jszwedko** [comment] 2016-09-09 04:05
Hi @arteev,

Thank you providing the sample code! The library technically only supports value types as the `cli.Flag`s (meaning there is a lack of test coverage for using pointers), but I'll see if I can address this particular issue. This does change in the `v2` branch which is intended to be released as v2 of this library eventually where pointers are used much more heavily (including the flags).

**Closed** 2016-09-11 15:42 UTC
