### ISSUE TITLE
Default boolean value

### ISSUE THREAD

**Issue by SirWindfield** [urfave/cli#689] opened 2017-11-29 15:58 UTC
I can't find any information on the web. I need a boolean flag that is false by default and can be toggled by simply passing `--flagname` instead of `--flagname true`. Is there something implemented in this cli?
I always get an `flag provided but not defined` error.

**Comment by jszwedko** [comment] 2017-11-29 17:51
Hi @SirWindfield,

That is the default behavior of the `BoolFlag`. Can you provide some sample code demonstrating the undefined flag error?

**Comment by SirWindfield** [comment] 2017-11-29 18:16
I created a [gist](https://gist.github.com/SirWindfield/7a0794f5566accab79c444a9bac907cf) holding the code. It fails at the global check flag. I enter the following command `./main --verbose parse <dir>`

**Comment by jszwedko** [comment] 2017-11-29 18:39
Thanks for the gist. I used that code, but was unable to reproduce.

Specifically, I did:

```go
package main

import (
	"fmt"
	"os"

	"github.com/urfave/cli"
)

func main() {
	app := cli.NewApp()

	app.Flags = []cli.Flag{
		cli.BoolFlag{
			Name:  "verbose",
			Usage: "Prints more verbose output to the console",
		},
		cli.BoolFlag{
			Name:  "dry, d",
			Usage: "Runs the algorithm without making any changes to the filesystem",
		},
	}

	app.Commands = []cli.Command{
		{
			Name:    "parse",
			Aliases: []string{"p"},
			Usage:   "Parse the specified directory",
			Action: func(c *cli.Context) {
				fmt.Printf("%+v\n", c.GlobalBool("verbose"))
			},
		},
	}

	app.Run(os.Args)
}
```

```
$ go run /tmp/tmp.go --verbose parse
true
```

**Comment by SirWindfield** [comment] 2017-11-29 18:48
Ok, looks like it is then probably some local file errors (maybe the repo isn't up to date or some stuff like that). Going to check real quick.

**Comment by lynncyrin** [comment] 2019-08-11 08:37
Similarly to jszwedko above, I don't think there's any bug here! So I'm going to close this. I can totally re-open it if someone can reproduce this issue 👍

**Closed by lynncyrin** 2019-08-11 08:37 UTC
