### ISSUE TITLE
v2 feature: Add Destination for StringSliceFlag

### ISSUE THREAD

**Issue by davidsbond** [urfave/cli#1075] opened 2020-02-25 11:16 UTC
## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

- My team want to start using the `Destination` values on flags so we can have our flag values strongly typed rather than stringly typed (i.e calling c.String("flag") etc.). I noticed that the `StringSliceFlag` does not have a `Destination` field like other flags do 
 
## Solution description

- Solution would be to add a `Destination` field to `StringSliceFlag` that works the same as all other `Destination` flag fields do.

**Comment by saschagrunert** [comment] 2020-02-25 11:55
I think this might be a valuable addition :)

**Comment by lynncyrin** [comment] 2020-02-26 05:12
See also => https://github.com/urfave/cli/issues/603 🙂

**Comment by tboerger** [comment] 2020-02-27 08:00
> Did you perform a search about this feature? Here's the Github guide about searching.

Not really searched for that, right? Till yesterday that issue have been even open and have been closed for being a duplicate of this issue here... https://github.com/urfave/cli/issues?q=is%3Aissue+StringSliceFlag+Destination+is%3Aclosed

**Comment by lynncyrin** [comment] 2020-02-27 15:55
@tboerger sorry you're having a hard time with the duplication thing! Is there something specific that you want here?

**Comment by davidsbond** [comment] 2020-02-27 16:10
@tboerger Sorry, obviously I didn't search very hard when I raised this. Agree mine should've been closed and yours left open. Happy for either issue to be used as long as it results in the feature being implemented.

**Comment by davidsbond** [comment] 2020-02-27 16:21
@lynncyrin I have some free tech time at work tomorrow so I can look into implementing this

**Comment by tboerger** [comment] 2020-02-27 16:50
It's more about the communication than marking something duplicate. The initial issue has been marked as claimed, which sounds like somebody would work on that, after some time nothing happened and I actively asked if I can help somehow as this lib is massively used in projects I'm involved and I haven't received any response. Just with the closing as duplicate comment I have seen that the claimed label have been removed.

I would just expect a tiny comment if somebody offers help. They issue is already nearly three years old.

**Comment by davidsbond** [comment] 2020-02-27 17:05
@tboerger I see what you mean. Well I'll be looking to raise PR to add this functionality sometime tomorrow, unless you'd like to do so yourself. 

I also notice there are a few more flags missing the `Destination` field. It might be worth aggregating all those and doing a single issue for missing `Destination` fields.

**Comment by tboerger** [comment] 2020-02-27 19:46
Go ahead, I would be happy to help testing.

**Comment by lynncyrin** [comment] 2020-02-27 22:57
Got it 👍 it wasn't previously clear to me that there's so much social complexity here 🙏 

@davidsbond I just assigned this to you 👍

**Comment by davidsbond** [comment] 2020-02-28 12:06
@lynncyrin @tboerger I think my PR is ready for review. Appears to work in my testing

**Closed** 2020-02-29 09:15 UTC
Labels: area/v2, status/claimed

**Comment by lynncyrin** [comment] 2020-02-29 09:17
The should go out in version `2.2.0` whenever someone feels so compelled to make another release
