### ISSUE TITLE
Add an `App.ProgramName`

### ISSUE THREAD

**Issue by purpleidea** [urfave/cli#783] opened 2018-11-22 16:56 UTC
## Motivation & Context

I have the following code:

```
app := cli.NewApp()
app.Name = "myprogramname"
```

I then add a sub command with the name "foo", and in that sub command I run:

```
func fooAction(c *cli.Context) error {
	program := c.App.Name
	log.Printf("program is: %s", program)
}
```

Unfortunately this prints "program is: `myprogramname foo`" instead of leaving out the "`foo`".
This is unexpected, particularly because the "program" did not change. If it is desired to have some sort of variable that appends the sub command names on it, then it should be something different. I use this variable to ascertain the "base name" of the program reliably, for log messages, etc...

## Requested Change

Add an `app.ProgramName`, that is always `myprogramname`, regardless of whether or not a particular subcommand is being executed.

---

_heavily edited by @lynncyrin!_

**Comment by lynncyrin** [comment] 2019-08-17 09:08
heya @purpleidea I understand the idea here, could you possibly refine it into a more concrete feature request? It's fine if not! I'm mostly looking to get us close to fixing this problem.

**Comment by purpleidea** [comment] 2019-08-19 18:55
Not sure what you're asking, but it's definitely a bug. The above reproducer I left should make it clear.

**Comment by lynncyrin** [comment] 2019-08-19 19:25
I'm trying to close to gap between "here is some problematic behavior" and "here is how we fix it". This particular problem has a clear problem case, but does not have a clear resolution.

For example, the simple solution of never changing `app.Name` based on the subcommand would definitely break anyone who currently relies on `myprogramname foo` behavior. One could take the position of _"`app.Name` should always be `myprogramname`"_

A non-breaking solution would be to create a `app.ProgramName` that's always `myprogramname`. But its unclear it the intention of that would be clear when compared with `app.Name`.

Essentially what I'm asking here is: I don't fully understand what specific change you are requesting, can you help clarify that?

**Comment by purpleidea** [comment] 2019-08-19 21:45
@lynncyrin 

> A non-breaking solution would be to create a app.ProgramName that's always myprogramname. But its unclear it the intention of that would be clear when compared with app.Name.

Sure, that would be fine, with a short docs patch that explains the difference. Cheers!

**Comment by lynncyrin** [comment] 2019-08-19 21:56
🚢 

This task is now free for anyone to take 👍  I'll be editing the OP to reflect the change that's needed here

**Comment by lynncyrin** [comment] 2019-11-27 06:49
Related issue => https://github.com/urfave/cli/issues/553

**Comment by lynncyrin** [comment] 2019-11-27 06:57
Per my comments above, I'm "re-branding" this to be a feature + documentation request. This ask here is fairly small IMO, so hopefully someone can drop in and grab it 🙏

**Comment by asahasrabuddhe** [comment] 2019-11-28 05:47
I tried to reproduce this issue on both v1 and v2 but could not replicate

```go
package main

import (
	"fmt"
	"github.com/urfave/cli"
	"log"
	"os"
)

func main() {
	app := cli.NewApp()
	app.Name = "myprogramname"
	app.Commands = []cli.Command{
		{
			Name: "foo",
			Action: func(c *cli.Context) error {
				program := c.App.Name
				fmt.Println("subcommand", program)
				return nil
			},
		},
	}

	app.Action = func(c *cli.Context) error {
		program := c.App.Name
		fmt.Println(program)
		return nil
	}

	log.Fatal(app.Run(os.Args))
}
```

```go
package main

import (
	"fmt"
	"github.com/urfave/cli/v2"
	"log"
	"os"
)

func main() {
	app := &cli.App{}
	app.Name = "myprogramname"
	app.Commands = cli.Commands{
		{
			Name: "foo",
			Action: func(c *cli.Context) error {
				program := c.App.Name
				fmt.Println("subcommand", program)
				return nil
			},
		},
	}

	app.Action = func(c *cli.Context) error {
		program := c.App.Name
		fmt.Println(program)
		return nil
	}

	log.Fatal(app.Run(os.Args))
}

```

For both the above codes, I am getting the correct program name from within the subcommand.

@lynncyrin you could try running this and then probably close this issue

**Comment by lynncyrin** [comment] 2019-11-29 02:53
I can repro this in both v1 and v2. Here's my repros:

---

v1

- https://github.com/lynncyrin/testing-cli/blob/urfave/cli/issues/783-v1-repro/main.go
- https://circleci.com/gh/lynncyrin/testing-cli/3

```
go run main.go
c.App.Name for app.Action is myprogramname
```

```
go run main.go foo
c.App.Name for app.Commands.Action is myprogramname foo
```

```
go run main.go foo bar
c.App.Name for App.Commands.Subcommands.Action is myprogramname foo
```

---

v2

- https://github.com/lynncyrin/testing-cli/blob/urfave/cli/issues/783-v2-repro/main.go
- https://circleci.com/gh/lynncyrin/testing-cli/4

```
go run main.go
c.App.Name for app.Action is myprogramname
```

```
go run main.go foo
c.App.Name for app.Commands.Action is myprogramname foo
```

```
go run main.go foo bar
c.App.Name for App.Commands.Subcommands.Action is myprogramname foo
```

**Comment by lynncyrin** [comment] 2019-11-29 02:57
To expand upon the original request, here's what I want to see happen here --

1. I want a  `ProgramName` with outputs like so

```
go run main.go
> myprogramname 

go run main.go foo
> myprogramname

go run main.go foo bar
> myprogramname
```

2. I also want a `CommandName` with outputs like so

```
go run main.go
> myprogramname 

go run main.go foo
> myprogramname foo

go run main.go foo bar
> myprogramname foo bar
```

3. I want `Name` to be removed in v3, cc https://github.com/urfave/cli/issues/833

**Comment by lynncyrin** [comment] 2019-11-29 02:59
Oh and, I would like to leave this issue open for new contributors 🙂 so anyone who drops into this issue is free to work on int

**Comment by lynncyrin** [comment] 2019-11-29 02:59
☝️ cc @urfave/cli as an FYI

**Comment by rliebz** [comment] 2019-12-05 13:17
I'm not sure that makes sense from an information ownership perspective. We're working with several namespaces here, each with distinct meanings, and our goal should be to preserve those meanings:`App`, `Command`, and `Context`. 

Currently the word "program" only appears in code comments, so I'm going to assume that it's synonymous with `App`.

I don't think that `c.App.Name` is ambiguous. It happens to be referenced from the `Context`, but it's a simple attribute access. The name of the `App` doesn't change when we run it—it should always be original `App`'s name. Changing this over the lifecycle of running a command is a bug. We don't need to rename this to `ProgramName` because `app.ProgramName` doesn't logically scope any different than `app.Name`. The `App` is the program.

Likewise, `c.Command.Name` is unambiguous. It's the name of the `Command` being run, which shouldn't ever change over the lifecycle of being run, so it shouldn't have any reference to the parent application.

The thing that owns the full run lineage is `Context`, so if we want a variable that for `go run main.go foo bar` produces `myprogramname foo bar`, that belongs on the `Context` as a read-only attribute, probably as a lightweight wrapper function over `Context.Lineage()`. I'll call it `Path()` for the sake of having something concrete to talk about, but I'm not tied to `Path()` in particular, and naming things is hard.

Following that design, we can preserve the mental model, avoid struct mutations while running the application, and be able to access all 3 things:

```go
func(c *cli.Context) error {
	fmt.Println(c.App.Name)     // myprogramname
	fmt.Println(c.Command.Name) // foo
	fmt.Println(c.Path())       // myprogramname foo
	return nil
}
```

The challenge with this approach is that it's not unlikely that people are relying on the current behavior of `Name`, so we'd have to figure out what to do between v1, v2, and v3, depending on if this is a "bug that needs fixing" or "change in behavior".

I'm also definitely open to other approaches, but the main consideration I have here is ensuring that information is attached to the appropriate scope in the application's lifecycle.

**Comment by lynncyrin** [comment] 2019-12-06 20:40
via @AudriusButkevicius in https://github.com/urfave/cli/pull/974

> I don't think we should add any public API, we should just fix App.Name to always be the same thing.
>
> I think command can be retrieved from the context, or if the user is generating functions (the only reason why I can explain you'd need a name), he could curry (functionally speaking) the name into the acting function.

**Comment by lynncyrin** [comment] 2019-12-06 20:41
via @asahasrabuddhe in https://github.com/urfave/cli/pull/974

> We actually have a ctx.Lineage call available which would return a slice of contexts from the current till the parent which would help the user do the same.

**Comment by lynncyrin** [comment] 2019-12-09 09:43
Hey, in case it's unclear - the current state of the world is that we need to come to a consensus on the desired solution here.

**Comment by rliebz** [comment] 2020-02-11 11:49
To avoid being blocked here, I'm going to propose we go with the following more conservative subset of what I proposed before:

- `c.App.Name` should no longer be modified during the course of the application. This will just be the application's name and will no longer reference command-related values
- If users need access to the previous behavior of `c.App.Name`, it can be built manually using the `Lineage` function on the `Context`.

Down the road we might decide it makes sense to expand the public API in some direction, but I think the above solves the original issue while keeping our API surface conservative.

**Comment by purpleidea** [comment] 2020-05-11 19:04
ping

**Comment by lynncyrin** [comment] 2020-05-14 04:45
I'll check in with this issue sometime soon! 👍

**Comment by dearchap** [comment] 2022-10-21 21:49
I verified that this has been fixed in v2 using following code

https://github.com/coilysiren/testing-cli/blob/urfave/cli/issues/783-v2-repro/main.go

```
$ go run main.go
c.App.Name for app.Action is myprogramname
$ go run main.go foo
c.App.Name for app.Commands.Action is myprogramname
$ go run main.go foo bar
c.App.Name for App.Commands.Subcommands.Action is myprogramname
```

App.Name is never modified. Help template uses App.HelpName or Command.HelpName which is modified based on the context. 

Given that I'm going to close this

Given that I'm going to close this

**Closed by dearchap** 2022-10-21 21:49 UTC
Labels: kind/feature, kind/discussion, area/v2, status/confirmed
