### ISSUE TITLE
Get incorrect value if a string contains wildcard character

### ISSUE THREAD

**Issue by life1347** [urfave/cli#778] opened 2018-10-22 06:33 UTC
Hi there, 

Recently I encountered a problem when trying to parse a wildcard path from user input. I want to provide a command to retrieve path (with the wildcard) from user input and show files under the path.

```
./cmd show  --path examples/python/*
```

And the structure of target path is

```
examples/python/
├── guestbook
├── hello.py
├── multifile
├── requestdata.py
├── sourcepkg
└── statuscode.py
```

Originally, I expected to get the result like 

```
[EXPECTED]
$ ./b show --path examples/python/*
>  examples/python/*
```

But got following instead

```
[WRONG]
$ ./b show --path examples/python/*
>  examples/python/guestbook
```

Following is source code tested with

```
package main

import (
  "fmt"
  "os"
  "github.com/urfave/cli"
)

func listall(c *cli.Context) error {
  arg := c.String("path")
  fmt.Println("> ", arg)
  return nil
}

func main() {
  app := cli.NewApp()
  pathFlag := cli.StringFlag{Name: "path", Usage: "File path"}
  app.Commands = []cli.Command{
    {Name: "show", Aliases: []string{}, Usage: "Show files", Flags: []cli.Flag{pathFlag}, Action: listall},
  }
  app.Run(os.Args)
}
```

After some more tests, I guess the problem is related to golang internal implementation. For example, 

```
package main

import (
    "fmt"
    "os"
)

func main() {
    arg := os.Args[1]
    fmt.Println(arg)
    fmt.Println(os.Args[1:])
}
```

The output will be like

```
./a examples/python/*
examples/python/guestbook
[examples/python/guestbook examples/python/hello.py examples/python/multifile examples/python/requestdata.py examples/python/sourcepkg examples/python/statuscode.py]
```

If a path contains wildcard, golang will parse it into multiple inputs instead of one. 

The current workaround is to use `" "` to quote the path which contains wildcard.

Here are the questions:

1. Does this problem consider as a bug?  

2. If it's not, do there have any way to get correct user input other than input quoted string? (though I expect the pkg should be able to handle such situation.)

Thanks for your help!  (this is a really awesome project btw.)

**Comment by ddnomad** [comment] 2018-10-25 14:50
1. Nope. The cause is shell globing. See: http://tldp.org/LDP/abs/html/globbingref.html
2. Nope. See https://stackoverflow.com/questions/11456403/stop-shell-wildcard-character-expansion (assuming you're using `bash` but most probably applies to other shells as well).

**Comment by lynncyrin** [comment] 2019-08-17 09:09
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue if there's still interest here!

**Closed by lynncyrin** 2019-08-17 09:09 UTC
