### ISSUE TITLE
context.App.Name incorrect in subcommands

### ISSUE THREAD

**Issue by therealbill** [urfave/cli#553] opened 2016-10-28 19:53 UTC
## Expected behavior

`c.App.Name` contains whatever was set in `app.Name` with no additions

## Observed behavior

`c.App.Name` contains whatever was set in `app.Name` PLUS a space then the name of the command.

## Context

In my code I call `NewApp()` then set `app.Name` as I've always done and the docs say. However, in my commands and subcommands I need to access this name and would rather not set a global for it. Thus, from context I use `c.App.Name` to get it. 

In commands this works perfectly. In sub-commands it does not. For subcommands `c.App.Name` is _changed_ to the "<app.Name> <command>".  The app's name should not change based on the command.

---

_lightly edited by @lynncyrin!_

**Comment by jszwedko** [comment] 2016-11-01 02:59
:+1: agreed, thanks for this report @therealbill. I took a stab just now, but the logic is more intertwined than I expected (the help message templates, `App.Name` and `Command.Name`, especially in the context of nested subcommands) so I'll have to revisit this when I have a bit more time to invest.

**Comment by lynncyrin** [comment] 2019-11-27 06:51
@asahasrabuddhe heya! I'm un-assigning ya since it's been a month with no movement on this. I want it to be available for anyone else to pick up 🙏

**Comment by lynncyrin** [comment] 2019-11-27 06:55
Having read through this issue a few times, I'm considering this a duplicate of https://github.com/urfave/cli/issues/783. Closing as a duplicate!

**Closed by lynncyrin** 2019-11-27 06:55 UTC
Labels: help wanted, status: confirmed, type: bug, version: v2
