### ISSUE TITLE
Does urfave cli meet the following requirements

### ISSUE THREAD

**Issue by rxliuli** [urfave/cli#1331] opened 2022-01-30 02:21 UTC
I tried to use urfave's api to do it, but I didn't find it, maybe I don't know?

````sh
saki run setup --filter libs/* # single filter parameter
saki run setup --filter libs/* apps/* # Multiple filter parameters
saki run --filter libs/* setup # swap the location of arguments and commands
saki exec --filter libs/* -- saki build lib # Execute arbitrary commands, split by --
````

**Comment by dearchap** [comment] 2022-10-21 22:04
3 is a duplicate of #1113 and will be discussed there.

**Closed by dearchap** 2022-10-21 22:04 UTC
Labels: kind/question, area/v2, status/triage
