### ISSUE TITLE
v2 feature: Ability to store objects in the cli.Context

### ISSUE THREAD

**Issue by NickLarsenNZ** [urfave/cli#1161] opened 2020-07-15 21:18 UTC
## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

Ability to add objects to `cli.Context`, making them available to anything that takes a Context (for example `Action()`, `Before()`, `After()`).

## Solution description

Assuming an application with one command which has a number of subcommands:

```sh
./app thing <list|stop|restart|delete>
```

Currently, each of the subcommands needs to instantiate a client (API client, or even just `http.Client`), and configuring it based on global or command flags. This leads to a lot of code duplication, and more work to refactor especially early on in development.

I would like to be able to create the client and make it available to all subcommand Actions (or `Before()`/`After()`).

## Example

The parent command has everything it needs to be able to configure the client and store it in the `cli.Context`

```go
var thing_command = &cli.Command{
	Name:  "thing",
	Flags: []cli.Flag{
		&cli.BoolFlag{
			Name:    "dry-run",
			Value:   false,
		},
	},
	Before: func(c *cli.Context) error {
		var client *myapi.Client
		if c.Bool("dry-run") {
			client, err := myapi.NewApiDryRunClient()
		} else {
			client, err := myapi.NewApiClient(&myapi.Config{
				BaseUrl: c.String("base-url"),
				ApiKey: c.String("api-key"),
				IgnoreTlsVerification: c.Bool("insecure"),
			})
		}

		// c.Set(name, value string) <-- can only store strings
		// Something like this would help a lot
		c.Store("client", &client)

		return err
	},
	Subcommands: []*cli.Command{
		thing_command_list,
	},
}
```

A subcommand of the above can then retrieve the pre-configured client from the context

```go
var thing_command_list = &cli.Command{
	Name:  "list",
	Action: func(c *cli.Context) error {
		var client *myapi.Client

		// Retrieve the already setup client
		client, err := c.Retrieve("client")
		if err != nil {
			return errors.Wrap(err, "unable to retrieve the pre-configured client")
		}
		
		fmt.Println(client.ListThings())

		return nil
	}
}

```

**Comment by rliebz** [comment] 2020-07-15 23:22
Would `Metadata` solve your use case? It's a `map[string]interface{}`, so effectively an arbitrary k/v store: https://github.com/urfave/cli/blob/v1.22.4/app.go#L91

**Comment by NickLarsenNZ** [comment] 2020-07-16 04:33
Hi @rliebz, yes I believe that would work just fine. Didn't realize it was right in front of me.

I'll try it then close the issue.

**Comment by rliebz** [comment] 2020-08-26 14:02
@lalloni I tried a program with effectively that same code, and I am seeing the context work correctly. 

Here is a complete program you can run:

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/urfave/cli/v2"
)

type contextKey string

const keyFoo contextKey = "foo"

func main() {
	app := cli.App{
		Before: func(c *cli.Context) error {
			c.Context = context.WithValue(c.Context, keyFoo, "foovalue")
			return nil
		},
		Commands: []*cli.Command{
			{
				Name: "cmd",
				Action: func(c *cli.Context) error {
					fmt.Println(c.Context.Value(keyFoo))
					return nil
				},
			},
		},
	}
	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}
```

Note that this still works if you pass a plain string as the context key, but that's [explicitly recommended against in the docs](https://golang.org/pkg/context/#WithValue), so I went ahead and did the idiomatic thing.

Since it sounds like the original issue is resolved, I'm going to go ahead and close this. @lalloni if you are still seeing issues storing values in the context, feel free to open up a new issue with an example of the code used to help us reproduce it.

**Closed by rliebz** 2020-08-26 14:02 UTC
Labels: area/v2, status/triage
