### ISSUE TITLE
"Flag provided but not defined" doesn't give enough details

### ISSUE THREAD

**Issue by coilysiren** [urfave/cli#852] opened 2019-08-10 22:39 UTC
"Flag provided but not defined" doesn't give enough details for end users who aren't specifically aware of how CLIs work. I get a lot of bug reports that are "I got this obscure error message, and I'm not sure what to do".

See also

- https://github.com/urfave/cli/issues/663
- https://github.com/urfave/cli/issues/744

**Comment by Zohvek** [comment] 2019-08-12 05:06
I'd like an opportunity to tackle this one. *working on it now*

**Comment by lynncyrin** [comment] 2019-08-12 05:11
@Zohvek yay cool! 🎉

**Comment by lynncyrin** [comment] 2019-08-29 02:59
Moving this one back to `help wanted` 📝

**Comment by arashout** [comment] 2019-10-22 23:27
I can try working on this, but what kind of error exactly would be more explicit than this?

Something like:
"The flag 'v' was passed but you did not define an associated flag in the configuration for 'v'" ?

I'm not sure that is any better? Do you have any suggestions @lynncyrin ?

**Comment by lynncyrin** [comment] 2020-01-21 04:26
> "The flag 'v' was passed but you did not define an associated flag in the configuration for 'v'" ?

This is closer, but still probably not verbose enough. There's also a few words / phrases that are likely to trip people up here, specifically:

- "was passed"
- "define an associated flag"
- "you did not define"

^ those all have meaning for CLI authors, but are likely not very understable for many CLI users. In particular there's the _"you did not define"_, which isn't true from the PoV of users.

Working from those points, here's my suggested error message:

> "You input the flag `v` but the `y` app does not accept that flag as an input."

the changes look like this:

- "was passed" => "you input"
- "define an associated flag" => "does not accept that flag"
- "you did not define" => "the `y` app"

**Comment by lynncyrin** [comment] 2020-01-21 04:32
I'm also vaguely skeptical that the casual user will know what the word "flag" means, so it might be better to remove that word from the error message entirely. On a related note, the "app" term only likely makes sense if you're a CLI author. So I'm thinking about an error message like this

> "You input `-v` but CLI `y` does not accept `-v` as an input."

**Comment by rliebz** [comment] 2020-01-21 14:12
A few examples of existing CLIs with error messages:
- `sed`: `sed: illegal option -- j`
- `awk`: `awk: unknown option -j ignored`
- `vim`: `Unknown option argument: "-j"`
- `emacs`: `Unknown option ‘-j’`
- `go`: `flag provided but not defined: -j`
- `git`: `unknown option: -j`
- `python`: `Unknown option: -j`
- `pip`: `no such option: -j`
- `node`: `/usr/local/bin/node: bad option: -j`
- `docker`: `unknown shorthand flag: 'j' in -j`

Fun fact: No CLI that I tried accepted a `-j` flag.

The word `flag` is almost always referred to as an `option`, so we should follow that example. 
I don't think things like including the CLI name are necessary, since users already have that information, but a handful of tools do include it. 

I'd stick with the most common pattern and probably just do `unknown option: -j`.

**Comment by lynncyrin** [comment] 2020-01-21 21:43
> I'd stick with the most common pattern and probably just do `unknown option: -j`

Your appraisal of the landscape is a good one 👍 That said, changing the error message to `unknown option: -j` would likely lead to a large increase in the amount of time I spent supporting users with this problem 😆 

So what I would like to see here is some capability that allows CLI authors to provide their own error messages for all of our errors.

**Comment by rliebz** [comment] 2020-01-24 00:36
I personally think there's value in a shorter error message compared to what we currently have. It may be confusing because it offers information that's irrelevant to the person trying to debug, rather than not offering enough context.

Regarding providing different error messages, I agree, that functionality is necessary. It looks like the `OnUsageError` field should be the current solution, but unfortunately it does not cover all usage scenarios. It handles `flag provided but not defined: -fake-flag`, `flag needs an argument: -arg-flag`, `invalid value "foo" for flag -int-flag: parse error`, but not `No help topic for 'fake-cmd'`. Not sure what other usage errors might exist.

**Comment by dearchap** [comment] 2022-10-27 15:32
Duplicate of #427

**Closed by dearchap** 2022-10-27 15:32 UTC
Labels: help wanted, kind/documentation, status/confirmed
